// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_rooms.sql

package db

import (
	"context"
	"database/sql"
)

const addChatRoomMember = `-- name: AddChatRoomMember :exec
INSERT INTO chat_room_members (room_id, user_id, joined_at, left_at)
VALUES (?, ?, ?, NULL)
ON CONFLICT(room_id, user_id) DO UPDATE SET
  left_at = NULL,
  joined_at = excluded.joined_at
`

type AddChatRoomMemberParams struct {
	RoomID   string
	UserID   string
	JoinedAt string
}

func (q *Queries) AddChatRoomMember(ctx context.Context, arg AddChatRoomMemberParams) error {
	_, err := q.db.ExecContext(ctx, addChatRoomMember, arg.RoomID, arg.UserID, arg.JoinedAt)
	return err
}

const createChatMessage = `-- name: CreateChatMessage :exec
INSERT INTO chat_messages (id, room_id, sender_id, sender_username, content, created_at, kind, media_url, mime_type, file_name, file_size)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChatMessageParams struct {
	ID             string
	RoomID         string
	SenderID       string
	SenderUsername string
	Content        string
	CreatedAt      string
	Kind           string
	MediaUrl       sql.NullString
	MimeType       sql.NullString
	FileName       sql.NullString
	FileSize       int64
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) error {
	_, err := q.db.ExecContext(ctx, createChatMessage,
		arg.ID,
		arg.RoomID,
		arg.SenderID,
		arg.SenderUsername,
		arg.Content,
		arg.CreatedAt,
		arg.Kind,
		arg.MediaUrl,
		arg.MimeType,
		arg.FileName,
		arg.FileSize,
	)
	return err
}

const createChatRoom = `-- name: CreateChatRoom :exec
INSERT INTO chat_rooms (id, owner_id, created_at, closed_at)
VALUES (?, ?, ?, NULL)
`

type CreateChatRoomParams struct {
	ID        string
	OwnerID   string
	CreatedAt string
}

func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) error {
	_, err := q.db.ExecContext(ctx, createChatRoom, arg.ID, arg.OwnerID, arg.CreatedAt)
	return err
}

const deleteChatRoomByIDAndOwner = `-- name: DeleteChatRoomByIDAndOwner :execrows
DELETE FROM chat_rooms
WHERE id = ?
 AND owner_id = ?
`

type DeleteChatRoomByIDAndOwnerParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteChatRoomByIDAndOwner(ctx context.Context, arg DeleteChatRoomByIDAndOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChatRoomByIDAndOwner, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveChatRoomsByUserID = `-- name: ListActiveChatRoomsByUserID :many
SELECT
  r.id,
  r.owner_id,
  r.created_at,
  r.closed_at
FROM chat_rooms r
JOIN chat_room_members m ON m.room_id = r.id
WHERE m.user_id = ?
  AND m.left_at IS NULL
  AND r.closed_at IS NULL
ORDER BY r.created_at DESC
`

func (q *Queries) ListActiveChatRoomsByUserID(ctx context.Context, userID string) ([]ChatRoom, error) {
	rows, err := q.db.QueryContext(ctx, listActiveChatRoomsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatRoom
	for rows.Next() {
		var i ChatRoom
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRoomMembersByRoomID = `-- name: ListActiveRoomMembersByRoomID :many
SELECT
  m.room_id,
  m.user_id,
  u.username,
  m.joined_at
FROM chat_room_members m
JOIN users u ON u.id = m.user_id
WHERE m.room_id = ?
  AND m.left_at IS NULL
ORDER BY m.joined_at ASC
`

type ListActiveRoomMembersByRoomIDRow struct {
	RoomID   string
	UserID   string
	Username string
	JoinedAt string
}

func (q *Queries) ListActiveRoomMembersByRoomID(ctx context.Context, roomID string) ([]ListActiveRoomMembersByRoomIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRoomMembersByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRoomMembersByRoomIDRow
	for rows.Next() {
		var i ListActiveRoomMembersByRoomIDRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Username,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessagesByRoomID = `-- name: ListRecentMessagesByRoomID :many
SELECT
  id,
  room_id,
  sender_id,
  sender_username,
  content,
  created_at,
  kind,
  media_url,
  mime_type,
  file_name,
  file_size
FROM chat_messages
WHERE room_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRecentMessagesByRoomIDParams struct {
	RoomID string
	Limit  int64
}

func (q *Queries) ListRecentMessagesByRoomID(ctx context.Context, arg ListRecentMessagesByRoomIDParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessagesByRoomID, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderUsername,
			&i.Content,
			&i.CreatedAt,
			&i.Kind,
			&i.MediaUrl,
			&i.MimeType,
			&i.FileName,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChatRoomMemberLeft = `-- name: MarkChatRoomMemberLeft :exec
UPDATE chat_room_members
SET left_at = ?
WHERE room_id = ?
  AND user_id = ?
  AND left_at IS NULL
`

type MarkChatRoomMemberLeftParams struct {
	LeftAt sql.NullString
	RoomID string
	UserID string
}

func (q *Queries) MarkChatRoomMemberLeft(ctx context.Context, arg MarkChatRoomMemberLeftParams) error {
	_, err := q.db.ExecContext(ctx, markChatRoomMemberLeft, arg.LeftAt, arg.RoomID, arg.UserID)
	return err
}
