// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package db

import (
	"context"
)

const createFriendRequest = `-- name: CreateFriendRequest :exec
INSERT INTO friend_requests(requester_id, target_id, created_at)
VALUES(?, ?, ?)
`

type CreateFriendRequestParams struct {
	RequesterID string
	TargetID    string
	CreatedAt   string
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, createFriendRequest, arg.RequesterID, arg.TargetID, arg.CreatedAt)
	return err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships(user_id, friend_id, created_at)
VALUES(?, ?, ?)
`

type CreateFriendshipParams struct {
	UserID    string
	FriendID  string
	CreatedAt string
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, createFriendship, arg.UserID, arg.FriendID, arg.CreatedAt)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user_id = ? AND friend_id = ?
`

type DeleteFriendshipParams struct {
	UserID   string
	FriendID string
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM friend_requests
WHERE requester_id = ? AND target_id = ?
`

type DeleteFriendRequestParams struct {
	RequesterID string
	TargetID    string
}

func (q *Queries) DeleteFriendRequest(ctx context.Context, arg DeleteFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequest, arg.RequesterID, arg.TargetID)
	return err
}

const deleteFriendRequestsBetween = `-- name: DeleteFriendRequestsBetween :exec
DELETE FROM friend_requests
WHERE (requester_id = ? AND target_id = ?) OR (requester_id = ? AND target_id = ?)
`

type DeleteFriendRequestsBetweenParams struct {
	RequesterID  string
	TargetID     string
	RequesterID2 string
	TargetID2    string
}

func (q *Queries) DeleteFriendRequestsBetween(ctx context.Context, arg DeleteFriendRequestsBetweenParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequestsBetween, arg.RequesterID, arg.TargetID, arg.RequesterID2, arg.TargetID2)
	return err
}

const friendshipExists = `-- name: FriendshipExists :one
SELECT COUNT(1)
FROM friendships
WHERE user_id = ? AND friend_id = ?
`

type FriendshipExistsParams struct {
	UserID   string
	FriendID string
}

func (q *Queries) FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, friendshipExists, arg.UserID, arg.FriendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const friendRequestExists = `-- name: FriendRequestExists :one
SELECT COUNT(1)
FROM friend_requests
WHERE requester_id = ? AND target_id = ?
`

type FriendRequestExistsParams struct {
	RequesterID string
	TargetID    string
}

func (q *Queries) FriendRequestExists(ctx context.Context, arg FriendRequestExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, friendRequestExists, arg.RequesterID, arg.TargetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listFriendsByUserID = `-- name: ListFriendsByUserID :many
SELECT u.id, u.email, u.username, u.password, u.created_at, u.updated_at
FROM friendships AS f
JOIN users AS u ON u.id = CASE
    WHEN f.user_id = ? THEN f.friend_id
    ELSE f.user_id
END
WHERE f.user_id = ? OR f.friend_id = ?
ORDER BY u.username
`

type ListFriendsByUserIDParams struct {
	UserID   string
	UserID_2 string
	FriendID string
}

func (q *Queries) ListFriendsByUserID(ctx context.Context, arg ListFriendsByUserIDParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listFriendsByUserID, arg.UserID, arg.UserID_2, arg.FriendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequestsByUserID = `-- name: ListIncomingFriendRequestsByUserID :many
SELECT u.id, u.email, u.username, u.password, u.created_at, u.updated_at
FROM friend_requests AS fr
JOIN users AS u ON u.id = fr.requester_id
WHERE fr.target_id = ?
ORDER BY fr.created_at DESC
`

func (q *Queries) ListIncomingFriendRequestsByUserID(ctx context.Context, targetID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listIncomingFriendRequestsByUserID, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email, &i.Username, &i.Password, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequestsByUserID = `-- name: ListOutgoingFriendRequestsByUserID :many
SELECT u.id, u.email, u.username, u.password, u.created_at, u.updated_at
FROM friend_requests AS fr
JOIN users AS u ON u.id = fr.target_id
WHERE fr.requester_id = ?
ORDER BY fr.created_at DESC
`

func (q *Queries) ListOutgoingFriendRequestsByUserID(ctx context.Context, requesterID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listOutgoingFriendRequestsByUserID, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email, &i.Username, &i.Password, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
