// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	CreatedAt string
	ExpiresAt string
	RevokedAt sql.NullString
}

type User struct {
	ID        string
	Email     string
	Username  string
	Password  string
	CreatedAt string
	UpdatedAt string
}
