// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ChatMessage struct {
	ID             string
	RoomID         string
	SenderID       string
	SenderUsername string
	Content        string
	CreatedAt      string
	Kind           string
	MediaUrl       sql.NullString
	MimeType       sql.NullString
	FileName       sql.NullString
	FileSize       int64
}

type ChatRoom struct {
	ID        string
	OwnerID   string
	CreatedAt string
	ClosedAt  sql.NullString
}

type ChatRoomMember struct {
	RoomID   string
	UserID   string
	JoinedAt string
	LeftAt   sql.NullString
}

type Friendship struct {
	UserID    string
	FriendID  string
	CreatedAt string
}

type FriendRequest struct {
	RequesterID string
	TargetID    string
	CreatedAt   string
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	CreatedAt string
	ExpiresAt string
	RevokedAt sql.NullString
}

type User struct {
	ID        string
	Email     string
	Username  string
	Password  string
	CreatedAt string
	UpdatedAt string
}
