// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package db

import (
	"context"
	"database/sql"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    created_at,
    expires_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, token_hash, created_at, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	ID        string
	UserID    string
	TokenHash string
	CreatedAt string
	ExpiresAt string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getValidRefreshToken = `-- name: GetValidRefreshToken :one
SELECT id, user_id, token_hash, created_at, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = ?
  AND revoked_at IS NULL
  AND expires_at > ?
LIMIT 1
`

type GetValidRefreshTokenParams struct {
	TokenHash string
	ExpiresAt string
}

func (q *Queries) GetValidRefreshToken(ctx context.Context, arg GetValidRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getValidRefreshToken, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = ?
WHERE token_hash = ?
`

type RevokeRefreshTokenParams struct {
	RevokedAt sql.NullString
	TokenHash string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.RevokedAt, arg.TokenHash)
	return err
}
