// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, email, username, password, created_at, updated_at)
VALUES(?, ?, ?, ?, ?, ?)
RETURNING id, email, username, password, created_at, updated_at
`

type CreateUserParams struct {
	ID        string
	Email     string
	Username  string
	Password  string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserFromDatabase = `-- name: DeleteUserFromDatabase :exec
DELETE FROM users
WHERE id=?
`

func (q *Queries) DeleteUserFromDatabase(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserFromDatabase, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password, created_at, updated_at FROM users
where email=?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersWithID = `-- name: GetUsersWithID :one
SELECT id, email, username, password, created_at, updated_at FROM users
WHERE id=?
`

func (q *Queries) GetUsersWithID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUsersWithID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
